### PR TITLE
Major PR: Linting, restructuring, new tests, bugfixes

### PR DESCRIPTION
**Pull request by benjaminLuoHC**
List of changes:

**Documentation**: Added WIP Sphinx documentation in the `docs/` folder
- Usage: Build the static website using `./make html` from the `docs/` directory. Afterward, go to the `build/` folder and open `index.html` in browser to locally view the static website 
- To do: Add content. All pages, routing, and theming is set up, but the raw content is missing
- Automation: The documentation is automatically built and deployed via the `sphinx.yml` GitHub actions script. This builds and extracts the `build/` file content to the `gh-pages` branch which gets automatically published to the repository's GitHub pages site: https://hc-sc-ocdo-bdpd.github.io/file-processing-tools. However, GitHub pages must be configured by a repository owner/admin 

**Linting**: Manually linted every `.py` file via PyLint. This was mostly changing spacing and rearranging imports

**Restructuring**: 
- Added folder to organize the `-processor.py` files
- Used `__init__.py` to auto-import classes when importing files. This enables us to use `from file_processing import File` instead of `from file_processing.file import File` (for every class)

**Tests**:
- Added file similarity tests. Test coverage is now 95%
- Patched file report access time test
- Replaced audio/transcription test files due to copyright issues
- Removed `utils/` folder as the simplified test cases do not require this level of analysis and no other files uses the class

**Other**:
- Rebuilt project (`dist/`)
- Moved dependencies to `pyproject.toml` instead of `requirements.txt` to enable installation of optional dependencies 
- Bugfix: Added conditional to check whether `pywin32` is installed before running related code
- CI/CD: Caching pip requirements and directory installing external dependencies instead of using marketplace extensions. Added a PyTest report step to view details on failing tests from the summary page

### CODE REVIEW

**Comment by pgaviganHC** [comment]
- All tests pass in the CI/CD pipeline: `295 passed, 12 warnings`
- All tests pass on local machine" `295 passed, 13 warnings`

Question: Do we know what is causing the warnings?

**Comment by pgaviganHC** [comment]
The WIP for the github.io page looks nice. I suggest we add links to the readmmme to point to the github.io page and vice versa pointing back to the repository.

**Comment by pgaviganHC** [comment]
With the switch to the toml file, is the requirements file deprecated? If so, can the toml file be used for generating the venv for desktop development of this library?

**Comment by benjaminLuoHC** [comment]
Follow up to test warnings:

**"FP16 is not supported on CPU; using FP32 instead"** (6 warnings)
* Cause: Triggers due to `whisper` (ie the transcription library). The default nature is to use `fp16` which is for GPU, but we have not configured the code to use cuda, so I forced it to use `fp16` which is the CPU version
* Band-aid: `model.transcribe(str(self._processor.file_path), fp16=False)` (`transcription_decorator.py`)

**"RuntimeWarning: overflow encountered in multiply"** (4 warnings)
* Cause: This occurred when trying to round tiny numbers in the file similarity file. I converted the similarities to `float64` to resolve this
* Fix: `sim = pd.DataFrame(similarities).astype('float64').round(2)`

**"DeprecationWarning: The distutils package is deprecated and slated for removal"** (1 warning)
* Cause: The `faiss-cpu` library uses a depreciated package. They have resolved it on their end but have not updated on `pypi` so we're stuck for the time being
* See: https://github.com/facebookresearch/faiss/blob/main/faiss/python/loader.py vs https://github.com/facebookresearch/faiss/blob/update_install_faiss1.7.4/faiss/python/loader.py (one uses from distutils.version import LooseVersion)
* Cannot fix on our end

**"DeprecationWarning: ../../../../../opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/pytesseract/pytesseract.py:38"** (1 warning)
* Cause: It seems `pytesseract` is using an older version of Pandas and does not have `pyarrow` as a dependency
* Cannot fix on our end

Will push updates now

**Comment by benjaminLuoHC** [comment]
> With the switch to the toml file, is the requirements file deprecated? If so, can the toml file be used for generating the venv for desktop development of this library?

I use the `requirements.txt` file for installing dependencies for the GitHub test runner. The `toml` file is for building the project (`python -m build`) which generates the `whl` file that gets uploaded to `pypi`. When users run `pip install <pypi_library>`, I believe they're effectively installing this `whl` file. The advent of the `toml` file is that we can specify optional dependencies unlike `requirements.txt`

For building the `venv` our goal would be to get our project to `pypi` so we can have the name of our project in `requirements.txt`

**Review by pgaviganHC — APPROVED** [review]
This PR is approved as it is a net positive for the project. There are some issues that remain that need to be addressed in follow up PRs.

- #143 with respect to updates to the requirements files
- #142 with respect to versions of pytersseract and whisper causing warnings
- #141 Tests of the file similarity functionality are needed
- #137 Need to finish the project documentation - include instructions for how to install the library, pointer to the example project repos (https://github.com/hc-sc-ocdo-bdpd/file_processing_tools_template), this repos, etc.
- #144 Investigate issue with directory tests failing inconsistently
- #145 Imporve use of whisper so that a GPU can be used if available (fall back to CPU if not)

**Review by BrennanHCSC — APPROVED** [review]

**Pull request merged**
