### PR TITLE
Test refactoring

### PR DESCRIPTION
**Pull request by taylenb**
Refactored tests for pptx and docx. Added conftest.py file for use of fixtures in tests. Currently all tests not passing for tests_ocr_decorator.py

### CODE REVIEW

**Comment by BrennanHCSC** [comment]
Let's wait until all tests are refactored to merge.

**Comment by taylenb** [comment]
> Let's wait until all tests are refactored to merge.

Alright. Suppose we can keep it as a draft until ready.

**Comment by benjaminLuoHC** [comment]
Can confirm that all tests pass, no files are modified during testing, and the PR has full test coverage. One suggestion I have is to modify the errors for corrupted files such that the only error thrown is `FileCorruptionError` instead of a mix with `FileProcessingFailedError` (as seen in `test_corrupted_files.py`)

**Comment by BrennanHCSC** [comment]
Great, I will go ahead and merge. Good observation with the mix of `FileCorruptionError` and `FileProcessingFailedError`. The challenge there was defining what specifically a corrupted file is. With some file types (like Microsoft files), this is very clear, but with others, it is more difficult. Any file types where a clear definition of 'corrupted' can be identified, `FileCorruptionError` can certainly be used instead.

**Pull request merged**
