### PR TITLE
Basic GUI

### PR DESCRIPTION
**Pull request by pgaviganHC**
A basic gui using Python Dash.

### CODE REVIEW

**Comment by pgaviganHC** [comment]
This may help: https://dash.plotly.com/dash-core-components/upload?_gl=1*1tkm3j1*_ga*ODAwOTczNzY4LjE2OTE2MTg3MTQ.*_ga_6G7EE0JNSC*MTY5MTYxODcxMy4xLjAuMTY5MTYxODcxMy42MC4wLjA

**Comment by pgaviganHC** [comment]
Having a hard time with the content encoding and can use some help.

The unit test cases are passing but the GUI run fails. The issue is that the GUI loads the file as a Base64 String. I'm having trouble getting that into a format that the table decoder can work with.

**Review by Louis-Boulet-HC — APPROVED** [review]
Looks good (from what I can gather), all tests pass 👍

**Review by zgaffarHC — COMMENTED** [review]
image
the tests cases pass but I was trying to run the GUI and I get this message and there are no output is generated

**Review by zgaffarHC — APPROVED** [review]
GUI Works, and test cases pass

**Comment by pgaviganHC** [comment]
I just did a rebase off main. We should rerun the checks to make sure it didn't break anything.

**Comment by pgaviganHC** [comment]
Tests all pass after rebase.

**Pull request merged**
