### PR TITLE
Fix to the general table box being cropped too close to its borders

### PR DESCRIPTION
**Pull request by Louis-Boulet-HC**
The find_table() function in the TableDetector class crops the table a little too much. As a result, I've coded lines to manually add extra padding around all sides of the table to expand the box enough so that the identified table fully fits into the cropping coordinates.

### CODE REVIEW

**Comment by Louis-Boulet-HC** [comment]
test_extract_table_content() currently failing, investigating

**Comment by Louis-Boulet-HC** [comment]
> test_extract_table_content() currently failing, investigating

- Test case now updated to reflect recent changes to the code
- Error was regarding leading/trailing zeroes getting removed when pandas read an excel file
     - Code now forces pd.read_excel() to read .xlsx files as string since automatic interpretation of some columns as integers made columns undergo unwanted formatting

**Review by zgaffarHC — APPROVED** [review]
test cases passed and output looks good

**Comment by fnwaohaHC** [comment]
Looks good! But do we need the new files added to the resources folder?

**Comment by Louis-Boulet-HC** [comment]
> Looks good! But do we need the new files added to the resources folder?

yes, they are being used for the updated extract content test case

**Review by fnwaohaHC — APPROVED** [review]

**Review by pgaviganHC — APPROVED** [review]

**Pull request merged**
