### PR TITLE
Various QoL changes and OCR output fix

### PR DESCRIPTION
**Pull request by Louis-Boulet-HC**
- Removal of extra "\n" characters outputted by OCR
     - solves previous problem causing Purity, Precision, & Recall to be calculated as zero
- Threshold increases to row and column limit minimums and thus remove impossibly small rows/cols
- Changed row_height default to "= 1" to reflect parameter behaviour (base multiplier is 1, previously "None")
- benchmark_pipeline.py quality of life changes
     - explicitly added all possibly variable parameters to generate table
          - will soon be used for randomizing table parameters in model test
     - now exporting true table to excel as well for extra comparison options
          - with "_true" suffix added
     - metrics_df cleaning
     - added error logging for failed table detection

### CODE REVIEW

**Review by pgaviganHC — COMMENTED** [review]
I see both test_calculate_row_column_limits() and test_extract_table_content() fail. Is this expected?

**Comment by fnwaohaHC** [comment]
> I see both test_calculate_row_column_limits() and test_extract_table_content() fail. Is this expected?

 test_calculate_row_column_limits() fails now because the thresholds were changed to 8 and 16. in the Table class. Testcase thresholds also need to be changed to match

**Comment by Louis-Boulet-HC** [comment]
@pgaviganHC the tests have been fixed (in table_test.py)
- For the test_calculate_row_column_limits(): row and column threshold values have been adjusted to reflect changes made earlier in the PR
     - values now changed to 8 & 16 respectively (lines 47-48)
- For the test_extract_table_content(): assertions have been overhauled
     - two assertions for dimension matching, one for row amount and one for column amount (lines 124-125)
     - new assertion(s) to ensure cell content matching by looping through cells that are known to be equal to one another by index numbers (lines 127-130)

**Comment by pgaviganHC** [comment]
> @pgaviganHC the tests have been fixed (in table_test.py)
> 
> * For the test_calculate_row_column_limits(): row and column threshold values have been adjusted to reflect changes made earlier in the PR
>   
>   * values now changed to 8 & 16 respectively (lines 47-48)
> * For the test_extract_table_content(): assertions have been overhauled
>   
>   * two assertions for dimension matching, one for row amount and one for column amount (lines 124-125)
>   * new assertion(s) to ensure cell content matching by looping through cells that are known to be equal to one another (lines 127-130)

Very good, the tests are all passing now!

**Review by pgaviganHC — APPROVED** [review]
Very good!

**Review by fnwaohaHC — APPROVED** [review]

**Pull request merged**
